# model params
backbone:

image_size: 640
num_class: 2

lambda1: 0.25
lambda2: 0.1
lambda3: 0.01

# anchor setting
use_anchors: True
anchor_type: 'faster-rcnn'   # yolo or faster-rcnn
base_anchors: [[16, 20.2, 25.4], [32, 40.3, 50.8], [64, 80.6, 101.6], [128, 161.3, 203.2], [256, 322.54, 406.37]]
anchor_ratios: [1, 1.5]   # list of h:w
feat_strides: [4, 8, 16, 32, 64]

# thresh
conf_thresh: 0.1
iou_thresh: 0.2
top_k: 1000     # just choose top k, if is neg, for example -1 resprent all - 1

# run params
batch_size: 16
epoch_num: 100
optimizer: 'ADAM'    # ADADELTA, ADAGRAD, ADAM, ADAMAX, FTRL, NADAM, RMSPROP, SGD
learning_rate: 0.0001
# paths

train_dir: '~/data/insightface/retinaface/train'
valid_dir: '~/data/insightface/retinaface/val'
test_dir: '~/data/insightface/retinaface/test'
ckpt_dir: '~/models/insightface/retinaface'
summary_dir: '~/logs/insightface/retinaface/summary'